version: '2'


services:


    # Main node user orchestration
    conductor:
      build: .
      image: "ipt/conductor"
      container_name: conductor
      ports:
        - "5000:5000"
      environment:
        - REDIS_AUTH
        - orchestra_key
        - URL_BASE
        - PROJECT
        - GREYFISH_URL
        - GREYFISH_REDIS_KEY
      command: go run traffic.go


    redis:
      image: 'redis:4-alpine'
      environment:
        - REDIS_AUTH
      command: redis-server --requirepass $REDIS_AUTH
      ports:
        - '6379:6379'
