<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<c:set var="contextPath" value="${pageContext.request.contextPath}"/>
<jsp:include page="base.jsp" />


<style>

  .col-container {
    display: table;
    width: 100%;
  }
  .col {
    display: table-cell;
    padding: 0.5%;
  }

  #rcorners_solid {
    border-radius: 0px;
    padding: 2%;
    width: 100%;
  }

</style>



<div class="col-container" style="width: 95%; padding-left: 5%;">
  <div class="col" style="background: transparent; width: 67%;">
    <h3>Interactive Parallelization Tool (IPT) Demystifies Parallel Programming</h3>
  </div>

  <div class="col" style="background:  transparent; width: 3%;">
  </div>

  <div class="col" style="background: transparent; width: 30%;">
    <h3>Project News</h3>
  </div>
</div>






<div class="col-container" style="width: 95%; padding-left: 5%;">
  <div class="col" style="background:  #f2f3c3; width: 67%; border-color: #b9aa16; border-style: solid; border-width: 1px;">
    <p>
      Interactive Parallelization Tool (IPT) helps in transforming multiple classes of C/C++ applications into parallel applications in a user-guided manner. The parallel programming paradigms currently supported by IPT include MPI, OpenMP, CUDA.     </p>
    <p>
      Now, IPT can be used from the convenience of the web-browser. It is simple. Start by creating an account on this website or use your existing TACC portal account information. If you login with your TACC portal account credentials, you will be also be able to compile and run the program generated by IPT on two XSEDE systems: Stampede2 and Comet.
    </p>


    <div class="col-container" style="width: 98%; padding-left: 2%;">
      <div class="col" style="background: transparent; width: 47.5%;">
        <img src="${contextPath}/resources/images/terminal_IPT.png" width="400" height="295" style="display: block; margin-left: auto; margin-right: auto;">
      </div>

      <div class="col" style="background:  transparent; width: 5%;">
      </div>

      <div class="col" style="background: transparent; ; width: 47.5%;">
        <iframe width="400" height="295" src="https://www.youtube.com/embed/qKo05dIZoYI"></iframe>
      </div>
    </div>

  </div>

  <div class="col" style="background:  transparent; width: 3%;">
  </div>


  <div class="col" style="background: #f2f3c3; border-color: #b9aa16; border-style: solid; width: 30%; border-width: 1px;">

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      As of March 1, 2020, the version of IPT provided on this website can only parallelize C programs.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A talk on code correctness in parallel programs will be given at the EduHiPC 2019 workshop in Hyderabad, India, on December 17, 2019.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A tutorial and talk on IPT was hosted at the Terna Engineering College in Mumbai, India on December 2, 2019.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A talk on IPT was given at the TACC booth during SC19.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A tutorial on IPT was held in TACC on October 18th, 2019 event held in Austin, TX.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A tutorial on IPT was held at the TACCSTER 2019 event held in Austin, TX.
    </p>

    <p id="rcorners_solid" style="background-color: #fcfcfc; ">
      A tutorial on IPT was held in TACC on September 14th, 2017 event held in Austin, TX.
    </p>

  </div>

</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="${contextPath}/resources/js/bootstrap.min.js"></script>


<jsp:include page="footer.jsp" />
