version: '3'


volumes:
  greyfish:


services:

  # Manager node: User orchestration
    manager_node:
        build: ./manager_node
        image: "ipt/manager_node"
        container_name: manager_node
        ports:
            - "5000:5000"
        volumes:
          - greyfish:/greyfish
        environment:
            - orchestra_key
            - URL_BASE
            - PROJECT
            - gthreads
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - SENDER_EMAIL
            - SENDER_EMAIL_PASSWORD
        command: "tail -F anything"


    # Cloud storage
    greyfish:
        build: ./greyfish_storage
        image: "ipt/greyfish"
        container_name: greyfish
        ports:
          - "2000-2004:2000-2004"
        volumes:
          - greyfish:/greyfish

        environment:
            - greyfish_key
            - greyfish_path
            - greyfish_threads
            - URL_BASE
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD

        command: "tail -F anything"


volumes:
  greyfish:
    external: true
